# Generated by Django 5.1.4 on 2025-01-07 15:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weather',
                'verbose_name_plural': 'Weather Records',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
